name: Command test

on:
  workflow_call:
    inputs:
      command_to_test:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test the command
        run: ${{ inputs.command_to_test }}
