# Tests a Shell script execution and checks whether an expected result file is
# created (if specified).
#
# Latest revision: 2026-03-04
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

name: Test Shell script

on:
  workflow_call:
    inputs:
      script_to_test:
        required: true
        type: string
      expected_file:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing previous result file (if any)
        if: inputs.expected_file != ''
        run: rm -f "${{ inputs.expected_file }}"

      - name: Make script executable
        run: chmod +x "${{ inputs.script_to_test }}"

      - name: Execute script
        run: |
          "${{ inputs.script_to_test }}"
          echo "Exited with code: $?"

      - name: Check the result file
        if: inputs.expected_file != ''
        run: |
          if [ -f "${{ inputs.expected_file }}" ]; then
            echo "${{ inputs.expected_file }} created succesfully."
          else
            "${{ inputs.expected_file }} was not created!" >&2
            exit 1
          fi
