# Tests a shell script execution and checks whether an expected result file is
# created (if specified).
#
# Latest revision: 2026-03-03
#
# Created and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read UNLICENSE file for details.

name: Test shell script

on:
  workflow_call:
    inputs:
      script_to_test:
        required: true
        type: string
      result_file_to_check:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove existing previous result file (if any)
        if: inputs.result_file != ''
        run: rm -f "${{ inputs.result_file }}"

      - name: Make script executable
        run: chmod +x "${{ inputs.script_name }}"

      - name: Execute script
        run: |
          "${{ inputs.script_name }}"
          echo "Exited with code: $?"

      - name: Check the result file
        if: inputs.result_file != ''
        run: |
          if [ -f "${{ inputs.result_file }}" ]; then
            echo "${{ inputs.result_file }} created succesfully."
          else
            "${{ inputs.result_file }} was not created!" >&2
            exit 1
          fi
